/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intexsoft_sensor_usb_UsbAdapter */

#ifndef _Included_com_intexsoft_sensor_usb_UsbAdapter
#define _Included_com_intexsoft_sensor_usb_UsbAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intexsoft_sensor_usb_UsbAdapter
 * Method:    getPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intexsoft_sensor_usb_UsbAdapter_getPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_intexsoft_sensor_usb_UsbAdapter
 * Method:    openDevice
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intexsoft_sensor_usb_UsbAdapter_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_intexsoft_sensor_usb_UsbAdapter
 * Method:    closeDevice
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intexsoft_sensor_usb_UsbAdapter_closeDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
